"""protect doctor availability slots

Revision ID: 7c5a2f44f86a
Revises: 6a4497badfa4
Create Date: 2026-01-15 17:31:14.399125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5a2f44f86a'
down_revision = '6a4497badfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('unique_doctor_slot', ['doctor_id', 'date', 'start_time', 'end_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.drop_constraint('unique_doctor_slot', type_='unique')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
